### PR TITLE
cleaned up commands and added new fun ones

### PR DESCRIPTION
**Pull request by DavidCaudill**

### CODE REVIEW

**Comment by System-Flenser** [comment]
Can one of the admins verify this patch?

**Comment by Eamnon** [comment]
looks good to me. +1

**Comment by Penguin2600** [comment]
this request is ok to test.

**Comment by Penguin2600** [comment]
test this please

**Comment by Eamnon** [comment]
do it fgt.

**Comment by Penguin2600** [comment]
this is ok to test

**Comment by Eamnon** [comment]
this is ok to test

**Comment by Penguin2600** [comment]
ok to test
test this please

**Comment by Penguin2600** [comment]
ok to test
test this please

**Comment by DavidCaudill** [comment]
this is ok to test

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Run%20Tox%20Config/4/
Test PASSed.

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Run%20Tox%20Config/5/
Test PASSed.

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Run%20Tox%20Config/6/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Run%20Tox%20Config/7/
Tests Passed, Yay.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Run%20Tox%20Config/8/

**Build Log**
_last 25 lines_

```
GitHub pull request #1 of commit 640e9ac48d02136ac1cc7565f46c788fcee5a462 automatically merged.
Setting status of 640e9ac48d02136ac1cc7565f46c788fcee5a462 to PENDING with url http://bock.systems:8080/job/Run%20Tox%20Config/8/ and message: Merged build started.
Building in workspace /var/lib/jenkins/jobs/Run Tox Config/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/TheInnerCircleO/icbot-config.git # timeout=10
Fetching upstream changes from https://github.com/TheInnerCircleO/icbot-config.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/TheInnerCircleO/icbot-config.git +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse refs/remotes/origin/pr/1/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/1/merge^{commit} # timeout=10
Checking out Revision 9560ff60ec1cdf13e0cda7284ed9107845e67537 (refs/remotes/origin/pr/1/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 9560ff60ec1cdf13e0cda7284ed9107845e67537
First time build. Skipping changelog.
[workspace] $ /bin/bash /tmp/hudson3170680666671088323.sh
ERROR: toxini file 'tox.ini' not found
Build step 'Execute shell' marked build as failure
Setting status of 640e9ac48d02136ac1cc7565f46c788fcee5a462 to FAILURE with url http://bock.systems:8080/job/Run%20Tox%20Config/8/ and message: Merged build finished.
```

Oh No...

**Comment by DavidCaudill** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Run%20Tox%20Config/9/
Tests Passed, Yay.

**Comment by DavidCaudill** [comment]
LOOKS GOOD TO ME =!

**Comment by uberscientist** [comment]
:+1: :+1:

**Pull request merged**
